DROP TABLE IF EXISTS `CNPJ_JC`.`TAB_HEADER`;
DROP TABLE IF EXISTS `CNPJ_JC`.`TAB_PRINCIPAL`;
DROP TABLE IF EXISTS `CNPJ_JC`.`TAB_SOCIOS`;
DROP TABLE IF EXISTS `CNPJ_JC`.`TAB_CNAE_SECUNDARIAS`;
DROP TABLE IF EXISTS `CNPJ_JC`.`TAB_TRAILLER`;