
DROP TABLESPACE IF EXISTS TBS_CNPJ;
DROP TABLE IF EXISTS CNPJ.TAB_HEADER;
DROP TABLE IF EXISTS CNPJ.TAB_PRINCIPAL;
DROP TABLE IF EXISTS CNPJ.TAB_SOCIOS;
DROP TABLE IF EXISTS CNPJ.TAB_CNAE_SECUNDARIAS;
DROP TABLE IF EXISTS CNPJ.TAB_TRAILLER;